| Name der Option                   | Default | Im Installer setzbar | in der Konfigdatei        |
|-----------------------------------|---------|----------------------|---------------------------|
| [-k](#parm_k)                     |  3      |        ja            | DEFAULT_KEEPBACKUPS       |
| [--keep_\<type\>](#parm_keepType) | Parameter für Option -k | nein | DEFAULT_KEEPBACKUPS_{DD\|DDZ\|TAR\|TGZ\|RSYNC} |
| [-l](#parm_l)                     | on      |  nein                | DEFAULT_LOG_LEVEL               |

